spring:
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver



  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    producer:
      acks: all
      properties:
        enable.idempotence: true


jwt:
  secret: ${JWT_SECRET}

internal:
  service.secret: ${INTERNAL_SERVICE_SECRET}

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8080
