spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/task_tracker_backend
    driver-class-name: org.postgresql.Driver


  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9094
      acks: all

      properties:
        enable.idempotence: true



#  config:
#    import: optional:file:.env

#jwt:
#  secret: ${JWT_SECRET}
jwt:
  secret: ER4sm2uhClZJk x5eps6/66AOpQA/xrTyU4nZtu6DBpw=
logging:
  level:
    org.springframework.security: DEBUG

